### ISSUE TITLE
The page doesn't load on chromebooks.

### ISSUE THREAD

**Issue by zqpvr** [ReMinecraftPE/mcpe#100]
I am hosting mcpe on my github for personal use and the page won't load, it's just a black screen.

**Comment by iProgramMC** [comment]
Ok, clearly it's not a problem with GitHub Pages itself because I was able to load the game on Windows.

![image](https://github.com/ReMinecraftPE/mcpe/assets/17717494/8f703b4e-4290-4154-af7c-893578078d85)

I'm... not sure. Are you able to open the dev tools on your Chromebook?
