### ISSUE TITLE
yo can i help code shit and help if so please add me to the github org so i can make changes

### ISSUE THREAD

**Issue by espero-dev** [ReMinecraftPE/mcpe#101]

**Comment by iProgramMC** [comment]
Sure, you can help code shit and help. However, I won't add you to the GitHub organization- I've actually added nobody so far. To contribute, simply fork the repository, commit the changes in YOUR fork, then submit a pull request.

**Comment by espero-dev** [comment]
dam why cant i get added to the org

**Comment by BrentDaMage** [comment]
you gotta prove yourself first

**Comment by espero-dev** [comment]
and how shell i do that

**Comment by BrentDaMage** [comment]
> and how shell i do that

prove to me that you can submit a pull request with an actually useful addition

**Comment by espero-dev** [comment]
what stuff do you want coded in?

**Comment by BrentDaMage** [comment]
> what stuff do you want coded in?

survival mode

**Comment by espero-dev** [comment]
k ill start that tomorrow

**Comment by iProgramMC** [comment]
I've said this once and I'll say it again - you won't get added. Actually I don't have plans to add anybody to the ReMinecraftPE organization.

If you want to contribute, create a pull request, wait for it to get merged, then you'll appear in the list of contributors on the front page of this repository.

Have fun!

**Comment by espero-dev** [comment]
why

**Comment by iProgramMC** [comment]
Because it's my project and I do what I want.

An actual reason would be that you di not need it to contribute. It's the principle of least access.

**Comment by iProgramMC** [comment]
P.S. I really didn't mean to reopen the issue
