### ISSUE TITLE
Getting this error "LINK1104 cannot open file 'dxguid.lib'

### ISSUE THREAD

**Issue by Vimd0** [ReMinecraftPE/mcpe#112]
Hello, I've been trying to build **ReMincraftPE** but keep getting this error **"LINK1104 cannot open file 'dxguid.lib'**. I followed all of the steps in the README and the tutorial video, but it still doesn't work. Is there anything else I should download because I have experience with Visual Studio and coding in general.

![Screenshot (330)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/ed746dad-8ad4-4ba8-8902-6d547dd222db)

Also, this is what it builds when it finishes.

![Screenshot (331)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/2432f044-9d8f-4139-9134-f47d59481ad9)

thx

**Comment by iProgramMC** [comment]
https://github.com/ReMinecraftPE/mcpe?tab=readme-ov-file#building

This says that you must install the DirectX SDK (June 2010). I don't blame you for not noticing it though, it's actually taken a while for me to find it even though I know it's there.

**Comment by Vimd0** [comment]
alr thx, I'll try looking into this.

**Comment by Vimd0** [comment]
Omg, thank you so much; it worked. Literally, all I had to do was install it, and everything worked perfectly! Also, I found an unused hotbar selection. :)

![Screenshot (333)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/563039c9-1180-481a-bf34-cbd3ea9d6680)
![img_741797](https://github.com/ReMinecraftPE/mcpe/assets/156633328/741ee245-498a-4529-98fd-3cf15580f21d)
