### ISSUE TITLE
Android Build ERROR "FAILURE: Build failed with exception."

### ISSUE THREAD

**Issue by Vimd0** [ReMinecraftPE/mcpe#114]
Hello, me again. I dug around in the Android platform and tried to run gradlew.bat but kept getting an error message. Also, I have no idea how to build for Android and have never created an Android app before. Some help would be greatly appreciated!

![Screenshot (339)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/0f8fc5db-8e5b-445d-89e9-54393019958e)

**Comment by TheBrokenRail** [comment]
This seems like an issue with your Gradle or Java installation. Try clearing your Gradle cache (there should be instructions online). Also, what version of Java are you using? It must be at least JDK 17.

Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Vimdo ***@***.***>
Sent: Tuesday, January 16, 2024 9:05:17 PM
To: ReMinecraftPE/mcpe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ReMinecraftPE/mcpe] Android Build ERROR "FAILURE: Build failed with exception." (Issue #114)


Hello, me again. I dug around in the Android platform and tried to run gradlew.bat but kept getting an error message. Also, I have no idea how to build for Android and have never created an Android app before. Some help would be greatly appreciated!

Screenshot.339.png (view on web)<https://github.com/ReMinecraftPE/mcpe/assets/156633328/0f8fc5db-8e5b-445d-89e9-54393019958e>

**Comment by AnnoyedUser420** [comment]
"via email" 💀

**Comment by Vimd0** [comment]
I'm using Java 8

**Comment by iProgramMC** [comment]
> "via email" 💀

Could you not?

**Comment by iProgramMC** [comment]
> I'm using Java 8

Try using a more up to date java version.  Java 8 came out on 18 March 2014.  Actually Java 8 is out of free support, you must pay Oracle to keep receiving security updates until 2030.

Source: https://en.wikipedia.org/wiki/Java_version_history

**Comment by uniformization** [comment]
Try downloading JDK 17 [here](https://adoptium.net/temurin/releases/) or whichever flavor you want, and add `-Dorg.gradle.java.home=C:\path\to\your\jdk17` to temporarily use JDK17 during the build. 
Or you can just change your `JAVA_HOME` environment variable to the directory of your JDK.

**Comment by Vimd0** [comment]
Okay, I finally got it to build, but I can't find the apk file. Am I missing a step? Is there anything I need to install? Am I doing something incorrect?


![Screenshot (405)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/41ef1276-0a84-4401-a032-056ff72e41b6)

![Screenshot (406)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/c409bf70-9fe8-4953-9600-57eeb1ae0da2)

**Comment by uniformization** [comment]
Looks like you only ran the `gradlew` batch script with no arguments. If you want to build from the command line, reference [this page](https://developer.android.com/build/building-cmdline#ReleaseMode) to build a release build and sign it. (required for release builds)

**Comment by Vimd0** [comment]
Alr, I try it.

**Comment by Vimd0** [comment]
Okay, I finally figured out how to build it, but none of the textures or UI will load. What now?

![womp womp](https://github.com/ReMinecraftPE/mcpe/assets/156633328/63e088e2-b7da-485d-9d88-5040dfb39477)

![Screenshot (421)](https://github.com/ReMinecraftPE/mcpe/assets/156633328/bd01cb15-6fba-4140-9002-a5a74dda2fe8)

**Comment by Vimd0** [comment]
So, I apparently put the asset folder in the wrong location when attempting to build it yesterday. Thats why it was loading everything. I finally figured out everything. Thank you for the fast responses and assistance in getting this thing up and running!

![Screenshot_20240124_213008_ReMinecraftPE](https://github.com/ReMinecraftPE/mcpe/assets/156633328/ce75dbbb-c711-43c5-94d8-193059652a1b)
