### ISSUE TITLE
Pressing the period key in a text input box gives wrong result

### ISSUE THREAD

**Issue by EpixScripts** [ReMinecraftPE/mcpe#19]
https://github.com/ReMinecraftPE/mcpe/blob/d8cdbe49138d91f91cea24c8ff66c57edb3f425b/source/GUI/TextInputBox.cpp#L87C30-L87C31

**Comment by iProgramMC** [comment]
Oops, will let you know when this is fixed

**Comment by iProgramMC** [comment]
Wow, it closes automatically. Great, because I meant to close it anyways
