### ISSUE TITLE
IDK what title I should add

### ISSUE THREAD

**Issue by JasiuWu2006** [ReMinecraftPE/mcpe#52]
It would be pretty cool if an EXE file would be made every time after compiling. An EXE file that can be opened straight from a shortcut.
I know you can kind of achieve this by making a shortcut to the project but you still have to compile everything again.
Thanks for your attention.

**Comment by iProgramMC** [comment]
This is totally untrue. The build artifacts for the Windows VS target are in windows_vs/bin/x64/[your configuration, debug or release]/minecraftcpp.exe . You have to make sure though that your assets are in the folder minecraftcpp.exe is running from (Visual Studio sets the working directory as [project root]/game)

**Comment by JasiuWu2006** [comment]
okay thanks

sob., 12 sie 2023, 20:18 użytkownik iProgramInCpp ***@***.***>
napisał:
