### ISSUE TITLE
Add Hide GUI option

### ISSUE THREAD

**Issue by JasiuWu2006** [ReMinecraftPE/mcpe#59]
Please add it either it can be hidden by f1 like in modern minecraft or as a toggleable option in the menu.

**Comment by iProgramMC** [comment]
not an issue, add it yourself

**Comment by BrentDaMage** [comment]
I think it'd be good to track what features should be added via issues. This one is pretty minor and having the issue here could help someone who's looking for something to do.

**Comment by BrentDaMage** [comment]
Or perhaps do feature requests on the Discord in the form of threads so people can expand on their ideas? No promises would need to be made that anything gets done, it'd just act as some inspiration for people looking for something to work on.

**Comment by iProgramMC** [comment]
Know what, sure.
