### ISSUE TITLE
Outline blocks instead of brightening them

### ISSUE THREAD

**Issue by JasiuWu2006** [ReMinecraftPE/mcpe#72]
It would be pretty cool if there was an option to outline selected blocks instead of making them brighter.
Please consider adding this.

**Comment by BrentDaMage** [comment]
I saw this in the Git feed and had so much hope that someone had just submitted a pull-request that implemented it. If I had to guess, iProgramInCpp wouldn't accept a pull-request for something like this since Minecraft: Pocket Edition did not use outlines in 2011 to highlight blocks.

**Comment by BrentDaMage** [comment]
Outlines are harder to see on mobile for one, but then again this could be solved by making this toggleable via a hidden property in options.txt.

**Comment by JasiuWu2006** [comment]
Now with bigger phone screens it would be vissible better. Also that's why I think this should be toggleable option in the game menu just like in modern MCPE/MCBE.

**Comment by iProgramMC** [comment]
Actually there is unused code for it in MCPE. However, the line is too thin, not sure why. Sure, you can add an option for it in a PR.

**Comment by iProgramMC** [comment]
PR #83 (integrated by commit [98d6b4e](https://github.com/ReMinecraftPE/mcpe/commit/98d6b4e5e82a18c1af8d5a2cffb085d3b33ce188)) fixed it.
