### ISSUE TITLE
Nether Reactor

### ISSUE THREAD

**Issue by JasiuWu2006** [ReMinecraftPE/mcpe#74]
How come no one suggested it yet?
I know it would be hard to implement but I belive it's possible to be backported.
The only downside is that you'd need to make a custom terrain.png with the nether reactor core and you'd need to atleast add a zombie or zombie pigman into the game.
Please consider adding this.

**Comment by iProgramMC** [comment]
No.

**Comment by Un1q32** [comment]
Maybe we have a server option to disable them even when they're implemented, since it could be a very powerful griefing tool, and even when not using it maliciously some server owners might just find the giant netherack monoliths unsightly.
