### ISSUE TITLE
Please make the always day mod a patch instead

### ISSUE THREAD

**Issue by JasiuWu2006** [ReMinecraftPE/mcpe#76]
I beg you. It would be pretty usefull and it would be much quicker than recompiling the game everytime.

**Comment by iProgramMC** [comment]
Many issues of yours are just suggestions, PLEASE STOP DOING THIS. THIS IS NOT AN ISSUE, AND SHOULD NOT BE POSTED IN THE ISSUES TAB. Feel free to implement it yourself or wait until someone else does.
