### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by TorutheRedFox** [ReMinecraftPE/mcpe#84]
it'd make sense to have a port to iOS that supports versions from the time period (iOS 3+ perhaps?)

**Comment by TheBrokenRail** [comment]
[SDL has iOS support](https://wiki.libsdl.org/SDL2/README/ios), but it's limited to iOS 8+.

**Comment by iProgramMC** [comment]
I'm sure it would! So, after I port the touch handling code from v0.1.1 or the v0.1.0 touch prototype, why not add iOS support? If SDL having support for only versions 8 and higher, you can always opt for a standard OpenGL ES view based application.

**Comment by TorutheRedFox** [comment]
> [SDL has iOS support](https://wiki.libsdl.org/SDL2/README/ios), but it's limited to iOS 8+.

older versions of SDL do exist and have been used to port things to iOS 6

xash3d has iOS 6 support for example

**Comment by TorutheRedFox** [comment]
as for having an iOS device, all you really need is access to Mac OS X 10.8 (Mountain Lion) or 10.9 (Mavericks) to run Xcode 4 or 5

it comes with a simulator (which really is just stripped down iOS compiled for x86 with an SDK of its own) which lets you run and test the app straight from Xcode

**Comment by iProgramMC** [comment]
Sure, but I don't have access to a Mac OS X device either!

**Comment by BrentDaMage** [comment]
I have access to all of those. I have an iPhone 4S running iOS 6.1.3 and multiple Macs running Snow Leopard and Lion with Xcode 4 installed. I think the best approach would be to write the most portable wrapper possible for the iOS-specific stuff just to get the app running. This would preferably be in C++ and not Objective C.

**Comment by iProgramMC** [comment]
I think it doesn't matter, since 99% of the MCPE code is the same across all platforms. The official MCPE has an Objective-C based frontend.

Of course it would be nice if SDL worked, but I'm not sure how it handles touch, among other things.

**Comment by BrentDaMage** [comment]
Poked around a bit with an Objective-C app on Xcode 4 with iOS 3 support. I'm likely just going to reverse-engineer/decompile the Objective-C for the first release of MCPE on iOS. There's only like two Objective-C classes that actually seem to matter in there too, so it may be really easy. We'll see... It should hopefully be easier than doing it from scratch.

**Comment by TorutheRedFox** [comment]
i'm actually not sure how ogl stuff is done on ios, but setting up views in general isn't too difficult and there's a sample ogles project in xcode that you can reference and even build off of

**Comment by BrentDaMage** [comment]
Can someone assign me to this issue? I'm currently working on decompiling the Objective-C portions of the iOS client.

**Comment by iProgramMC** [comment]
Sure.

**Comment by BrentDaMage** [comment]
@iProgramMC This is ready to be closed, we just need to update the README to mention the fact that iOS 3.0 and above is supported.

**Comment by TorutheRedFox** [comment]
i'll close it in that case then
